application: presidenciables2013
version: 2-3
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /css
  static_dir: css
  expiration: 5m

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /results
  script: results.py
  login: admin

- url: /favicon.ico
  static_files: icon/favicon.ico
  upload: icon/favicon.ico

- url: /robots.txt
  static_files: robots/robots.txt
  upload: robots/robots.txt

- url: /worker/result
  script: results.py
  login: admin

- url: /load
  script: voto.py
  login: admin

- url: /build
  script: voto.py
  login: admin

- url: /init
  script: voto.py
  login: admin

- url: /.*
  script: voto.py

