application: presidenciables2013
version: 1-8
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /css
  static_dir: css
  expiration: 1m

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /results
  script: results.py

- url: /worker/result
  script: results.py

- url: /.*
  script: voto.py

